### ISSUE TITLE
Exception: rule.forEach is not a function

### ISSUE THREAD

**Issue by ggyorfi** [daidodo/tsimportsorter#25]
**Code snippet triggering the exception**
```ts
// INSERT CODE HERE
```

**Logs**
(Please select ALL logs in "JS/TS Import/Export Sorter" Output window and copy/paste here)
```
[2020-10-17T23:30:30.574] [INFO] formatDocument - config: {
  configurationFileName: 'import-sorter.json',
  autoFormat: 'onSave',
  formatExports: true,
  exclude: [ 'node_modules' ],
  excludeGlob: [],
  groupRules: [
    '^react(-dom)?$',
    {},
    '^@optika',
    '^~/',
    '^../',
    '^./(?!style)',
    '^./style'
  ],
  sortRules: { paths: '', names: [ '_', 'aA' ] },
  keepUnused: [ { path: '.*' } ],
  EmptyLinesBetweenGroups: 1,
  maxBindingNamesPerLine: 3,
  maxDefaultAndBindingNamesPerLine: 4,
  maxExportNamesPerLine: 0,
  maxNamesPerWrappedLine: 1,
  insertFinalNewline: true,
  maxLineLength: 80,
  tabType: 'space',
  tabSize: 2,
  hasSemicolon: false,
  quoteMark: 'double',
  trailingComma: 'multiLine',
  bracketSpacing: true,
  eol: 'LF'
}
[2020-10-17T23:30:30.574] [INFO] formatDocument - tsCompilerOptions: undefined
[2020-10-17T23:30:30.575] [INFO] formatDocument - fileName: /Users/ggyorfi/Projects/bridge/src/__tests__/parser.spec.js
[2020-10-17T23:30:30.578] [INFO] parser.formatSource - composeConfig: {
  maxLength: 80,
  maxWords: {
    withoutDefault: 3,
    withDefault: 4,
    wrapped: 1,
    exported: 9007199254740991
  },
  groupSep: '\n\n',
  tab: '  ',
  quote: [Function],
  comma: ',',
  semi: '',
  bracket: [Function],
  lastNewLine: true,
  nl: '\n'
}
[2020-10-17T23:30:30.578] [ERROR] formatDocument - Found exception: [TypeError: rule.forEach is not a function
	at comparatorFromRule (Project/out/format/sort/compare.js:142:54)
	at Object.sorterFromRules (Project/out/format/sort/compare.js:9:68)
	at Object.formatSource (Project/out/format/main/index.js:43:27)
	at formatDocument (Project/out/extension.js:79:34)
	at sortImportsBeforeSavingDocument (Project/out/extension.js:54:27)
	at Project/out/extension.js:21:75
	at t.ExtHostDocumentSaveParticipant._deliverEventAsync (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:621:150)
	at t.ExtHostDocumentSaveParticipant._deliverEventAsyncAndBlameBadListeners (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:620:396)
	at t.ExtHostDocumentSaveParticipant.$participateInSave (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:620:98)
	at g._doInvokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:860:464)
	at g._invokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:860:156)
	at g._receiveRequest (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:858:817)
	at g._receiveOneMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:857:623)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:855:691
	at l.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:46:475)
	at v.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:256:381)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:1047:649
	at l.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:46:475)
	at v.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:256:381)
	at t.PersistentProtocol._receiveMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:261:451)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:258:489
	at l.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:46:475)
	at p.acceptChunk (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:253:851)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:253:203
	at Socket.t (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:263:54)
	at Socket.emit (events.js:223:5)
	at addChunk (_stream_readable.js:309:12)
	at readableAddChunk (_stream_readable.js:290:11)
	at Socket.Readable.push (_stream_readable.js:224:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:181:23)]
```

**Comment by daidodo** [comment]
@ggyorfi Thanks for your feedback!

May I have the following info for investigation:
1. What's your OS?
2. What's the version of your VSCode?
3. What's the code snippet causing the problem?

**Comment by daidodo** [comment]
Hi @ggyorfi,

I'll close this issue since it's outdated.
Please check out the latest release v4.1.1 and feel free to re-open it if you ever encounter the issue again.
Thanks!
